### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by SteveMacenski** [facontidavide/Treexy#1]
Hi,

Can you indicate the motivation of this over OpenVDB if this is more or less a reimplementation of it? 

(also, love that logo, did you make that?!)

**Comment by facontidavide** [comment]
I am glad you ask, also because I learn about OpenVDB thanks to **spatio_temporal_voxel_layer**. :wink: 

My number one motivation is fun: I love coding.

But as a roboticist, I have the following motivation:

- I want to build a drop-in replacement of OctomMap.
- OpenVDB is a big library with a lot of terms focused on computer graphics. Its size and documentation is intimidating for roboticists. I want to create a small and easy-to-read one, with an easy-to-integrate, header-only, core.
- Third reason...

![image](https://user-images.githubusercontent.com/2822888/137589323-04e0deb2-27f8-455d-9056-a5be070bcc00.png)

**Comment by SteveMacenski** [comment]
It'll probably be quite awhile before I circle back to this, I can only handle 2 big projects at a time :laughing:. Once I'm done with some planning and control work, this will be back on my agenda. But this is cool to see!

**Comment by YoshuaNava** [comment]
@facontidavide Sorry for bringing back this issue to life :slightly_smiling_face: 

I'm interested in this library and in the insights you present in https://github.com/facontidavide/Bonxai/issues/1#issuecomment-946078079.

I wanted to ask you two questions, if it isn't much bother:

1. Is Treexy/Bonxai also based on a B+ tree as OpenVDB?
2. Is the difference in the number of internal nodes equivalent to using [openvdb::Tree3](https://github.com/AcademySoftwareFoundation/openvdb/blob/master/openvdb/openvdb/tree/Tree.h#L1095) or something else entirely?
3. Can you explain a bit the memory allocation strategy for Treexy?
  a. In the scenario of a point being inserted into Treexy, what is allocated? Which elements of the tree topology and data containers are added into the tree?
  b. Do you allocate voxels sparsely, or by blocks?
  c. A grosso modo, what strategy do you have in mind to represent free space?
  d. What are your target scenarios? More particle/point clouds, or level-sets/SDF?


Thank you very much in advance.

Best regards,
Yoshua

**Comment by YoshuaNava** [comment]
HI @facontidavide,
I was wondering if you had time to look at my recent question in this issue.

Thank you very much in advance.

**Comment by facontidavide** [comment]
- voxels allocated by blocks
- main difference with openvdb is the fact that there is 1 level less in the data hierarchy (inner layer)
- about free space... if you can't find a voxel, it is not there. No strategy
- goal of the library: point cloud processing, in particular as alternative to Octrees

**Comment by YoshuaNava** [comment]
I see. Thanks for the reply. Bonxai looks quite solid.

Have you considered pushing back to the OpenVDB upstream some of the changes? Since the introduction of Bonxai, nanovdb was merged to the master branch, and there is also a templated type within the OpenVDB definitions that creates a tree with one layer less.
